version: '3.7'

services: 
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    volumes: 
     - ./backend:/src
    depends_on: 
      - postgres
      - minio
    ports: 
      - 8000:8000
      - 5002:5002

  postgres:
    image: postgres:12-alpine
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # volumes:
      # - postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  minio:
    image: minio/minio
    ports: 
      - 9000:9000
    environment: 
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    command: server /data
# volumes:
  # postgres: